name: Deploy to Cloud Run

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure gcloud project
      run: gcloud config set project instant-medium-460400-h2

    - name: Build and push Docker image
      run: gcloud builds submit --tag gcr.io/instant-medium-460400-h2/mi-api .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy mi-api \
          --image gcr.io/instant-medium-460400-h2/mi-api \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
          --set-env-vars "ConnectionStrings__DefaultConnection=Server=127.0.0.1,1433;Database=BUMP;User Id=sqlserver;Password=root123;TrustServerCertificate=True;"
